# Generated by Django 3.1.4 on 2021-01-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cafe',
        ),
    ]
