# Generated by Django 3.1.4 on 2021-01-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='description',
            new_name='address',
        ),
    ]
