# Generated by Django 3.1.4 on 2021-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210118_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='dhakal', max_length=5),
        ),
    ]
