# Generated by Django 3.1.4 on 2021-01-18 13:32

from django.db import migrations
import v1.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210118_1510'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', v1.core.models.CustomUserManager()),
            ],
        ),
    ]
