# Generated by Django 3.1.4 on 2021-01-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='created_by',
            new_name='user',
        ),
    ]
