# Generated by Django 3.1.4 on 2021-01-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20210109_1623'),
        ('item', '0004_auto_20210110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='cafe.cafe'),
        ),
    ]
